# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(657, 487)
        MainWindow.setMinimumSize(QtCore.QSize(657, 487))
        MainWindow.setMaximumSize(QtCore.QSize(657, 487))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-80, -50, 803, 541))
        self.widget.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.widget.setObjectName("widget")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(260, 170, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(200, 320, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(350, 320, 123, 39))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.comboBox.setObjectName("comboBox")
        self.criar = QtWidgets.QPushButton(self.widget)
        self.criar.setGeometry(QtCore.QRect(480, 320, 123, 39))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.criar.setFont(font)
        self.criar.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.criar.setObjectName("criar")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(200, 370, 150, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setGeometry(QtCore.QRect(350, 370, 123, 39))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.Entrar = QtWidgets.QPushButton(self.widget)
        self.Entrar.setGeometry(QtCore.QRect(480, 370, 123, 39))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Entrar.setFont(font)
        self.Entrar.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.Entrar.setObjectName("Entrar")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(350, 120, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(-1, -21, 661, 511))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(70, 70, 510, 391))
        self.widget_3.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.widget_3)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(160, 280, 201, 80))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.resultado = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.resultado.setFont(font)
        self.resultado.setObjectName("resultado")
        self.horizontalLayout_3.addWidget(self.resultado)
        self.resultado.raise_()
        self.label_8.raise_()
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        self.label_12.setGeometry(QtCore.QRect(140, 100, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.palpite = QtWidgets.QWidget(self.widget_2)
        self.palpite.setGeometry(QtCore.QRect(0, 20, 661, 491))
        self.palpite.setObjectName("palpite")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.palpite)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(180, 350, 281, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.label_11 = QtWidgets.QLabel(self.palpite)
        self.label_11.setGeometry(QtCore.QRect(30, 180, 101, 32))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.Palpites = QtWidgets.QLabel(self.palpite)
        self.Palpites.setGeometry(QtCore.QRect(180, 90, 441, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Palpites.setFont(font)
        self.Palpites.setObjectName("Palpites")
        self.label_10 = QtWidgets.QLabel(self.palpite)
        self.label_10.setGeometry(QtCore.QRect(31, 90, 131, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(self.palpite)
        self.label_7.setGeometry(QtCore.QRect(30, 230, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.palpite)
        self.label_5.setGeometry(QtCore.QRect(31, 51, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Tema = QtWidgets.QLabel(self.palpite)
        self.Tema.setGeometry(QtCore.QRect(109, 51, 61, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Tema.setFont(font)
        self.Tema.setObjectName("Tema")
        self.tela_escolha = QtWidgets.QWidget(self.widget_2)
        self.tela_escolha.setGeometry(QtCore.QRect(0, 20, 661, 491))
        self.tela_escolha.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.tela_escolha.setObjectName("tela_escolha")
        self.Frutas = QtWidgets.QPushButton(self.tela_escolha)
        self.Frutas.setGeometry(QtCore.QRect(120, 120, 91, 41))
        self.Frutas.setSizeIncrement(QtCore.QSize(123, 39))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Frutas.setFont(font)
        self.Frutas.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.Frutas.setObjectName("Frutas")
        self.Cores = QtWidgets.QPushButton(self.tela_escolha)
        self.Cores.setGeometry(QtCore.QRect(230, 120, 91, 41))
        self.Cores.setSizeIncrement(QtCore.QSize(123, 39))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Cores.setFont(font)
        self.Cores.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.Cores.setObjectName("Cores")
        self.Animais = QtWidgets.QPushButton(self.tela_escolha)
        self.Animais.setGeometry(QtCore.QRect(340, 120, 91, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Animais.setFont(font)
        self.Animais.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.Animais.setObjectName("Animais")
        self.Paises = QtWidgets.QPushButton(self.tela_escolha)
        self.Paises.setGeometry(QtCore.QRect(450, 120, 91, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Paises.setFont(font)
        self.Paises.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.Paises.setObjectName("Paises")
        self.label_4 = QtWidgets.QLabel(self.tela_escolha)
        self.label_4.setGeometry(QtCore.QRect(180, 50, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Aguarde = QtWidgets.QWidget(self.tela_escolha)
        self.Aguarde.setGeometry(QtCore.QRect(-90, -60, 751, 551))
        self.Aguarde.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.Aguarde.setObjectName("Aguarde")
        self.label_3 = QtWidgets.QLabel(self.Aguarde)
        self.label_3.setGeometry(QtCore.QRect(120, 150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(self.Aguarde)
        self.progressBar.setGeometry(QtCore.QRect(120, 190, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.widget_2.raise_()
        self.widget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Animais.clicked['bool'].connect(self.tela_escolha.hide)
        self.Frutas.clicked['bool'].connect(self.tela_escolha.hide)
        self.Cores.clicked['bool'].connect(self.tela_escolha.hide)
        self.Paises.clicked['bool'].connect(self.tela_escolha.hide)
        self.Entrar.clicked['bool'].connect(self.widget.hide)
        self.criar.clicked['bool'].connect(self.widget.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Qual é a Palavra?"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Ativar nova sala</p></body></html>"))
        self.criar.setText(_translate("MainWindow", "Criar"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Escolher uma sala</p></body></html>"))
        self.Entrar.setText(_translate("MainWindow", "entrar"))
        self.label_13.setText(_translate("MainWindow", "Bem Vindo ao"))
        self.label_8.setText(_translate("MainWindow", "Resultado:"))
        self.resultado.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "FIM DO JOGO"))
        self.label_6.setText(_translate("MainWindow", "Digite uma letra"))
        self.pushButton_3.setText(_translate("MainWindow", "Palpite"))
        self.label_11.setText(_translate("MainWindow", "Status:"))
        self.Palpites.setText(_translate("MainWindow", "[]"))
        self.label_10.setText(_translate("MainWindow", "Letras utilizadas:"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Palavra</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Tema:"))
        self.Tema.setText(_translate("MainWindow", "Variavel"))
        self.Frutas.setText(_translate("MainWindow", "Frutas"))
        self.Cores.setText(_translate("MainWindow", "Cores"))
        self.Animais.setText(_translate("MainWindow", "Animais"))
        self.Paises.setText(_translate("MainWindow", "Países"))
        self.label_4.setText(_translate("MainWindow", "Escolha uma categoria"))
        self.label_3.setText(_translate("MainWindow", "Aguarde"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())