# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-80, -50, 731, 531))
        self.widget.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(130, 100, 200, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.criar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.criar.setObjectName("criar")
        self.horizontalLayout.addWidget(self.criar)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(130, 170, 501, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.Entrar = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Entrar.setObjectName("Entrar")
        self.horizontalLayout_2.addWidget(self.Entrar)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(-1, -21, 661, 511))
        self.widget_2.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.widget_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 60, 171, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 210, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(50, 300, 511, 161))
        self.widget_3.setStyleSheet("background-color: rgb(233, 185, 110);")
        self.widget_3.setObjectName("widget_3")
        self.palpite = QtWidgets.QWidget(self.widget_2)
        self.palpite.setGeometry(QtCore.QRect(50, 300, 511, 161))
        self.palpite.setObjectName("palpite")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.palpite)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 281, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.tela_escolha = QtWidgets.QWidget(self.widget_2)
        self.tela_escolha.setGeometry(QtCore.QRect(20, 40, 561, 411))
        self.tela_escolha.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.tela_escolha.setObjectName("tela_escolha")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tela_escolha)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(50, 30, 421, 80))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.comboBox.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.escolha = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.escolha.setObjectName("escolha")
        self.horizontalLayout_3.addWidget(self.escolha)
        self.widget_3.raise_()
        self.palpite.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.verticalLayoutWidget.raise_()
        self.tela_escolha.raise_()
        self.widget_2.raise_()
        self.widget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.criar.clicked['bool'].connect(self.widget.hide)
        self.pushButton_3.clicked['bool'].connect(self.palpite.hide)
        self.escolha.clicked['bool'].connect(self.tela_escolha.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Criar nova sala:"))
        self.criar.setText(_translate("MainWindow", "Criar"))
        self.label_2.setText(_translate("MainWindow", "Digite o código da sala que deseja entrar"))
        self.Entrar.setText(_translate("MainWindow", "entrar"))
        self.label_5.setText(_translate("MainWindow", "Tema:"))
        self.label_3.setText(_translate("MainWindow", "Variavel"))
        self.label_7.setText(_translate("MainWindow", "Palavra"))
        self.label_6.setText(_translate("MainWindow", "Digite uma letra"))
        self.pushButton_3.setText(_translate("MainWindow", "Palpite"))
        self.label_4.setText(_translate("MainWindow", "Escolha uma categoria"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Frutas"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Cores"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Animais"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Países"))
        self.escolha.setText(_translate("MainWindow", "Escolher"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
